//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotWeb.WebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class 網頁L
    {
        public int id { get; set; }
        public Nullable<int> kid { get; set; }
        public string 網頁名稱 { get; set; }
        public bool 開啟 { get; set; }
        public System.DateTime 時間 { get; set; }
        public int 排序 { get; set; }
        public string 網頁內容 { get; set; }
        public Nullable<bool> C_隱藏 { get; set; }
        public Nullable<int> C_新增人員 { get; set; }
        public Nullable<int> C_新增單位 { get; set; }
        public Nullable<System.DateTime> C_新增日期 { get; set; }
        public Nullable<int> C_修改人員 { get; set; }
        public Nullable<int> C_修改單位 { get; set; }
        public Nullable<System.DateTime> C_修改日期 { get; set; }
        public string C_語系 { get; set; }
    }
}
