//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強型別資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具產生。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建 Visual Studio 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResWeb {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResWeb() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ResWeb", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強型別資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 中央大學薄膜技術中心 的當地語系化字串。
        /// </summary>
        internal static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 驗證碼不正確 的當地語系化字串。
        /// </summary>
        internal static string Error_Valide {
            get {
                return ResourceManager.GetString("Error_Valide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 連接伺服器發生錯誤，請聯絡管理員。 的當地語系化字串。
        /// </summary>
        internal static string Err_ConnectionServerOut {
            get {
                return ResourceManager.GetString("Err_ConnectionServerOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 帳號已處於登錄狀態無法完成 的當地語系化字串。
        /// </summary>
        internal static string Err_LoginState {
            get {
                return ResourceManager.GetString("Err_LoginState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 登入失敗，請重新輸Email及密碼。 的當地語系化字串。
        /// </summary>
        internal static string Err_LoginUnCorrect {
            get {
                return ResourceManager.GetString("Err_LoginUnCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請先登錄以完成該項作業 的當地語系化字串。
        /// </summary>
        internal static string Err_LogoutState {
            get {
                return ResourceManager.GetString("Err_LogoutState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 電子郵件已存在，請勿重複註冊。 的當地語系化字串。
        /// </summary>
        internal static string Err_MailHasExist {
            get {
                return ResourceManager.GetString("Err_MailHasExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 郵件帳號不存在 的當地語系化字串。
        /// </summary>
        internal static string Err_MailNotExist {
            get {
                return ResourceManager.GetString("Err_MailNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 密碼確認不符 的當地語系化字串。
        /// </summary>
        internal static string Err_npwdNotEqualspwd {
            get {
                return ResourceManager.GetString("Err_npwdNotEqualspwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新密碼不可等於舊密碼 的當地語系化字串。
        /// </summary>
        internal static string Err_opwdEqualnpwd {
            get {
                return ResourceManager.GetString("Err_opwdEqualnpwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 該筆訂單已支付過 的當地語系化字串。
        /// </summary>
        internal static string Err_PayHasFinished {
            get {
                return ResourceManager.GetString("Err_PayHasFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 各密碼欄位不可以有空白 的當地語系化字串。
        /// </summary>
        internal static string Err_pwdHasBlank {
            get {
                return ResourceManager.GetString("Err_pwdHasBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 系統發生Session遺失，請聯絡管理員。 的當地語系化字串。
        /// </summary>
        internal static string Err_SessionLost {
            get {
                return ResourceManager.GetString("Err_SessionLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 系統錯誤 的當地語系化字串。
        /// </summary>
        internal static string Err_System {
            get {
                return ResourceManager.GetString("Err_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 中央大學薄膜技術中心 的當地語系化字串。
        /// </summary>
        internal static string keywords {
            get {
                return ResourceManager.GetString("keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 http://www.lp99miracle.com 的當地語系化字串。
        /// </summary>
        internal static string PublicUrl {
            get {
                return ResourceManager.GetString("PublicUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 中央大學薄膜技術中心 的當地語系化字串。
        /// </summary>
        internal static string WebTitle {
            get {
                return ResourceManager.GetString("WebTitle", resourceCulture);
            }
        }
    }
}
